format: yamanifest
version: 1.0
---
work/atmosphere/um_hg3.exe-20240305:
  fullpath: /g/data/tm70/pcl851/src/penguian/access-esm-build-gadi/bin/um_hg3.exe-20240305
  hashes:
    binhash: c00cdb97594ecddd6467e8a8648c495b
    md5: f3f03fcffb4187e9c51b487ad24455fa
work/ice/cicexx:
  fullpath: /g/data/access/payu/access-esm/bin/coe/cicexx
  hashes:
    binhash: 612c5f22405c074531e5d415bdc32a02
    md5: 2d8befa0957c1196f8ba387f36b7c1ef
work/ocean/mom5xx:
  fullpath: /g/data/access/payu/access-esm/bin/coe/mom5xx
  hashes:
    binhash: 892a661fe3c35d2e7add6b2fbf041984
    md5: 9b3592016605846dfda306a81ed9579c
